### ISSUE TITLE
Translation into pt_BR (Brazilian Portuguese)

### ISSUE THREAD

**Issue by rogeriopradoj** [danielkummer/git-flow-cheatsheet#1]
Hello, @danielkummer 

First, congrats for the work, nice job!

I'd like to translate the project into pt_BR, and for that I'm forking the repo.

How you suggest me to organize the translation:
- a folder language
- a folder pt-br in root
- any other way

Thanks in advance!

**Comment by danielkummer** [comment]
Hi @rogeriopradoj first - thanks for your effort!

I'd suggest a file index.pt_BR.html in the root directory with a language link to en and vice versa...
