### ISSUE TITLE
Can Git Flow interoperate between two different repositories

### ISSUE THREAD

**Issue by jasonborne** [danielkummer/git-flow-cheatsheet#22]
For Eg: 

I have repo named FRUITS having branches apple, banana and I have SMOOTHY having branches apple, banana and blueberry. 

Now, lets say SMOOTHY is a team repo and FRUITS is the main repo. How will git flow work if I had to create a feature from SMOOTHY and then merge it into the apple branch in FRUITS repo. ? 

Again I do like the idea of git flow, I am just trying to understand how can it fit our needs. 

Thanks,
Ishan

**Comment by rogeriopradoj** [comment]
Hi, @jasonborne . I suggest you to take a look at this page: https://www.atlassian.com/git/workflows.

There you can get a lot of information about git workflows besides "gitflow".

Good luck!

**Comment by danielkummer** [comment]
Hi @jasonborne I'm afraid I have to go with @rogeriopradoj s' comment - I'm not quite how your case can work with git-flow, maybe pull requests would better accommodate your needs...
