### ISSUE TITLE
Provide more details or a link about "git-flow is a merge based solution"

### ISSUE THREAD

**Issue by webxl** [danielkummer/git-flow-cheatsheet#5]

**Comment by rogeriopradoj** [comment]
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/

**Comment by danielkummer** [comment]
Thanks to @rogeriopradoj for the rebase link - very good and simple explanation!

**Comment by danielkummer** [comment]
Added a wiki page containing the link mentioned above. The wiki is also a good place to collect additional information.

**Comment by rogeriopradoj** [comment]
Oh, yeah, @danielkummer , my pleasure! Keep on the good work!
